#!/usr/bin/env python3
"""Generate Swift models for the Codex App Server account methods.

The input is the schema checked in under ``schemas/appserver``, which is emitted
verbatim by the installed ``codex`` binary (``make schema-sync``). Transcribing
that contract by hand is how the original spec draft acquired four wrong field
names, so the models are generated instead and CI asserts the generated file
matches the schema it came from.

Only the three account responses AgentBar actually reads are generated, along
with the definitions those three can reach. ``schemas/appserver/v2`` holds 249
per-file roots at Codex ``0.148.0``; generating all of them would be a large
unused surface with no owner.

Drift is caught by ``make check-generated``, which regenerates and asks git
whether anything moved — the comparison has to happen after swift-format, so it
belongs in the Makefile rather than in a ``--check`` flag here.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "schemas" / "appserver" / "v2"
OUTPUT = ROOT / "Sources" / "CodexAppServer" / "Generated" / "AppServerAccountModels.swift"

# The roots to generate, in the order they appear in the output.
ROOTS = [
    "GetAccountResponse",
    "GetAccountRateLimitsResponse",
    "GetAccountTokenUsageResponse",
]

# Fields the generator deliberately drops, as ``Type.property``.
#
# Not an oversight and not transcription: AgentBar has no use for the account's
# identity, and a field that is never decoded is a field that cannot be logged,
# stored or leaked by a later change. The schema still declares it; this file
# records that we decline it.
SUPPRESSED_FIELDS = {
    "ChatgptAccount.email": "AgentBar never holds the account's identity.",
    "GetAccountTokenUsageResponse.threadUsage": (
        "AgentBar shows what is left, never what was spent."
    ),
}

HEADER = """\
// Generated by scripts/generate-appserver-models.py from schemas/appserver/v2.
// Do not edit. Run `make generate-models` after `make schema-sync`.
//
// The Codex App Server ships its own protocol schema, so these types are
// derived from the contract the installed binary declares rather than
// transcribed from prose. Everything the schema marks nullable is optional
// here, every string enum tolerates a value this build has never heard of, and
// every collection drops an element it cannot read rather than failing whole.
//
// Fields the generator deliberately omits:
{suppressed}

import Foundation
"""


# ── naming ────────────────────────────────────────────────────────────────────


def lower_camel(raw: str) -> str:
    """``self_serve_business_prolite`` → ``selfServeBusinessProlite``."""
    parts = re.split(r"[_\-\s]+", raw)
    if not parts:
        return raw
    head, *rest = parts
    return head[:1].lower() + head[1:] + "".join(p[:1].upper() + p[1:] for p in rest)


def escaped(name: str) -> str:
    reserved = {"default", "for", "in", "case", "class", "enum", "struct", "return", "self"}
    return f"`{name}`" if name in reserved else name


# ── schema traversal ──────────────────────────────────────────────────────────


def load_roots() -> tuple[dict[str, dict], list[tuple[str, dict]]]:
    """Collects shared definitions and the root objects, in ROOTS order."""
    definitions: dict[str, dict] = {}
    roots: list[tuple[str, dict]] = []
    for root in ROOTS:
        path = SCHEMA_DIR / f"{root}.json"
        if not path.exists():
            sys.exit(f"error: {path} is missing — run `make schema-sync`")
        document = json.loads(path.read_text())
        for name, node in document.get("definitions", {}).items():
            existing = definitions.get(name)
            if existing is not None and existing != node:
                # Two roots disagreeing about a shared type means the schema
                # itself is inconsistent, and picking one silently would put a
                # wrong contract in the build.
                sys.exit(f"error: definition {name} differs between roots")
            definitions[name] = node
        roots.append((root, {k: v for k, v in document.items() if k != "definitions"}))
    return definitions, roots


def is_null(node: dict) -> bool:
    return node.get("type") == "null"


def unwrap_nullable(node: dict) -> tuple[dict, bool]:
    """Returns the non-null branch and whether null was one of the options."""
    if "anyOf" in node:
        branches = [b for b in node["anyOf"] if not is_null(b)]
        nullable = len(branches) != len(node["anyOf"])
        if len(branches) == 1:
            inner, inner_nullable = unwrap_nullable(branches[0])
            return inner, nullable or inner_nullable
    if "allOf" in node and len(node["allOf"]) == 1:
        return unwrap_nullable(node["allOf"][0])
    kind = node.get("type")
    if isinstance(kind, list):
        concrete = [k for k in kind if k != "null"]
        if len(concrete) == 1:
            reduced = dict(node)
            reduced["type"] = concrete[0]
            return reduced, "null" in kind
    return node, False


def swift_type(node: dict) -> tuple[str, bool]:
    """Maps a schema node onto a Swift type and whether it is optional."""
    node, nullable = unwrap_nullable(node)

    ref = node.get("$ref")
    if ref:
        return ref.rsplit("/", 1)[-1], nullable

    kind = node.get("type")
    if kind == "string":
        return "String", nullable
    if kind == "boolean":
        return "Bool", nullable
    if kind == "integer":
        return {"int32": "Int32", "int64": "Int64"}.get(node.get("format"), "Int"), nullable
    if kind == "number":
        return "Double", nullable
    if kind == "array":
        element, _ = swift_type(node["items"])
        return f"[{element}]", nullable
    if kind == "object":
        additional = node.get("additionalProperties")
        if isinstance(additional, dict):
            value, _ = swift_type(additional)
            return f"[String: {value}]", nullable
    sys.exit(f"error: unsupported schema node {json.dumps(node)[:200]}")


def is_collection(swift: str) -> bool:
    return swift.startswith("[")


def wrapped_type(swift: str) -> str | None:
    """The element type of a collection whose elements are generated types."""
    if not is_collection(swift):
        return None
    inner = swift[1:-1]
    if ": " in inner:
        inner = inner.split(": ", 1)[1]
    return inner if inner[0].isupper() and inner not in {"String", "Bool", "Int"} else None


# ── emission ──────────────────────────────────────────────────────────────────


def doc(node: dict, indent: str) -> list[str]:
    description = node.get("description")
    if not description:
        return []
    lines: list[str] = []
    for paragraph in description.split("\n"):
        text = paragraph.strip()
        if not text:
            lines.append(f"{indent}///")
            continue
        # Wrapped at 92 so the 4-space indent still fits swift-format's 100.
        current = f"{indent}///"
        for word in text.split():
            if len(current) + 1 + len(word) > 96:
                lines.append(current)
                current = f"{indent}///"
            current += f" {word}"
        lines.append(current)
    return lines


def emit_string_enum(name: str, node: dict) -> list[str]:
    cases = [(lower_camel(v), v) for v in node["enum"]]
    out = doc(node, "")
    out += [
        f"public enum {name}: Sendable, Hashable, Decodable {{",
    ]
    for swift_case, raw in cases:
        out.append(f"    case {escaped(swift_case)}")
        _ = raw
    out += [
        "    /// A value this build has never heard of. Schema drift degrades to a",
        "    /// name the interface can still show, never to a decoding failure.",
        "    case unrecognised(String)",
        "",
        "    public init(rawValue: String) {",
        "        switch rawValue {",
    ]
    for swift_case, raw in cases:
        out.append(f'        case "{raw}": self = .{escaped(swift_case)}')
    out += [
        "        default: self = .unrecognised(rawValue)",
        "        }",
        "    }",
        "",
        "    public var rawValue: String {",
        "        switch self {",
    ]
    for swift_case, raw in cases:
        out.append(f'        case .{escaped(swift_case)}: "{raw}"')
    out += [
        "        case .unrecognised(let value): value",
        "        }",
        "    }",
        "",
        "    public init(from decoder: any Decoder) throws {",
        "        self.init(rawValue: try decoder.singleValueContainer().decode(String.self))",
        "    }",
        "}",
        "",
    ]
    return out


def properties_of(name: str, node: dict) -> list[tuple[str, str, bool, dict]]:
    """(json key, swift type, optional, node) for every property we keep."""
    required = set(node.get("required", []))
    kept: list[tuple[str, str, bool, dict]] = []
    for key, child in node.get("properties", {}).items():
        if f"{name}.{key}" in SUPPRESSED_FIELDS:
            continue
        swift, nullable = swift_type(child)
        optional = nullable or key not in required
        # A schema default makes an absent boolean concrete rather than optional.
        if optional and "default" in child and swift == "Bool" and not nullable:
            optional = False
        kept.append((key, swift, optional, child))
    return kept


def emit_struct(name: str, node: dict) -> list[str]:
    fields = properties_of(name, node)
    out = doc(node, "")
    for key in sorted(SUPPRESSED_FIELDS):
        if key.startswith(f"{name}."):
            # Wrapped like any other doc comment: an unwrapped one is a
            # lint failure a maintainer would have to trace back to a reason
            # string they lengthened by a word.
            out += doc(
                {
                    "description": f"`{key.split('.', 1)[1]}` is deliberately not "
                    f"decoded — {SUPPRESSED_FIELDS[key]}"
                },
                "",
            )
    out.append(f"public struct {name}: Sendable, Hashable, Decodable {{")
    for key, swift, optional, child in fields:
        out += doc(child, "    ")
        out.append(f"    public let {escaped(lower_camel(key))}: {swift}{'?' if optional else ''}")
    out.append("")

    # Memberwise initialiser: the tests build these directly, and the compiler
    # withholds the synthesised one once `init(from:)` is written by hand.
    if fields:
        out.append("    public init(")
        for index, (key, swift, optional, child) in enumerate(fields):
            default = " = nil" if optional else (" = false" if child.get("default") is False else "")
            comma = "," if index < len(fields) - 1 else ""
            out.append(
                f"        {escaped(lower_camel(key))}: {swift}{'?' if optional else ''}"
                f"{default}{comma}"
            )
        out.append("    ) {")
        for key, _, _, _ in fields:
            prop = lower_camel(key)
            out.append(f"        self.{escaped(prop)} = {escaped(prop)}")
        out.append("    }")
    else:
        out.append("    public init() {}")
    out.append("")

    out.append("    private enum CodingKeys: String, CodingKey {")
    for key, _, _, _ in fields:
        prop = lower_camel(key)
        out.append(f"        case {escaped(prop)}" + (f' = "{key}"' if prop != key else ""))
    out.append("    }")
    out.append("")
    out.append("    public init(from decoder: any Decoder) throws {")
    if fields:
        out.append("        let container = try decoder.container(keyedBy: CodingKeys.self)")
    for key, swift, optional, child in fields:
        prop = escaped(lower_camel(key))
        element = wrapped_type(swift)
        if element:
            # A map or list whose elements are generated types: one unreadable
            # entry must not cost the caller every other entry.
            call = "decodeLenientIfPresent" if optional else "decodeLenient"
            out.append(f"        {prop} = try container.{call}({swift}.self, forKey: .{prop})")
        elif optional:
            out.append(
                f"        {prop} = try container.decodeIfPresent({swift}.self, forKey: .{prop})"
            )
        else:
            fallback = child.get("default")
            if fallback is False:
                out.append(
                    f"        {prop} = try container.decodeIfPresent({swift}.self, "
                    f"forKey: .{prop}) ?? false"
                )
            else:
                out.append(f"        {prop} = try container.decode({swift}.self, forKey: .{prop})")
    out.append("    }")
    out.append("}")
    out.append("")
    return out


def emit_union(name: str, node: dict) -> list[str]:
    """A ``oneOf`` discriminated by a single-valued ``type`` enum."""
    branches = []
    for branch in node["oneOf"]:
        title = branch.get("title") or sys.exit(f"error: untitled branch in {name}")
        discriminator = branch["properties"]["type"]["enum"][0]
        branches.append((title, discriminator, branch))

    out: list[str] = []
    for title, _, branch in branches:
        out += emit_struct(title, branch)

    out += doc(node, "")
    out.append(f"public enum {name}: Sendable, Hashable, Decodable {{")
    for title, discriminator, _ in branches:
        out.append(f"    case {lower_camel(discriminator)}({title})")
    out += [
        "    /// A kind of account this build does not know. Reported rather than",
        "    /// rejected: the caller's answer is the same either way — no limits.",
        "    case unrecognised(type: String)",
        "",
        "    private enum Discriminator: String, CodingKey { case type }",
        "",
        "    public init(from decoder: any Decoder) throws {",
        "        let kind = try decoder.container(keyedBy: Discriminator.self)",
        "            .decode(String.self, forKey: .type)",
        "        switch kind {",
    ]
    for title, discriminator, _ in branches:
        out.append(
            f'        case "{discriminator}": '
            f"self = .{lower_camel(discriminator)}(try {title}(from: decoder))"
        )
    out += [
        "        default: self = .unrecognised(type: kind)",
        "        }",
        "    }",
        "}",
        "",
    ]
    return out


def emit(name: str, node: dict) -> list[str]:
    if "enum" in node:
        return emit_string_enum(name, node)
    if "oneOf" in node:
        return emit_union(name, node)
    return emit_struct(name, node)


def referenced_types(node: object, owner: str | None = None) -> set[str]:
    """Definition names ``node`` reaches, following the suppression list.

    ``owner`` is the definition the properties belong to, which is what makes a
    suppressed field's own subtree invisible here.
    """
    found: set[str] = set()
    if isinstance(node, dict):
        for key, child in node.items():
            if key == "$ref" and isinstance(child, str):
                found.add(child.rsplit("/", 1)[-1])
            elif key == "properties" and owner is not None and isinstance(child, dict):
                for prop, value in child.items():
                    if f"{owner}.{prop}" in SUPPRESSED_FIELDS:
                        continue
                    found |= referenced_types(value)
            elif key == "oneOf" and isinstance(child, list):
                # A union's branches are emitted as structs under their own
                # titles, so suppression is keyed on the branch — matching
                # ``emit_union`` → ``emit_struct`` → ``properties_of``. Walking
                # them under the union's name instead would let a declined
                # branch field keep its type in the build.
                for branch in child:
                    title = branch.get("title") if isinstance(branch, dict) else None
                    found |= referenced_types(branch, title)
            else:
                found |= referenced_types(child)
    elif isinstance(node, list):
        for child in node:
            found |= referenced_types(child)
    return found


def reachable_definitions(definitions: dict[str, dict], roots: list[tuple[str, dict]]) -> set[str]:
    """The definitions the generated roots can actually arrive at.

    Declining a field has to drop the types only that field reached, or the
    surface AgentBar refused to decode stays in the build under another name.
    Pruning is otherwise inert: every definition the three roots carry is
    reachable, so this removes nothing that anything reads.
    """
    seen: set[str] = set()
    frontier: set[str] = set()
    for name, node in roots:
        frontier |= referenced_types(node, name)
    while frontier:
        name = frontier.pop()
        if name in seen or name not in definitions:
            continue
        seen.add(name)
        frontier |= referenced_types(definitions[name], name)
    return seen


def dependency_order(definitions: dict[str, dict]) -> list[str]:
    """Alphabetical: Swift needs no forward declarations, and stable output
    matters more than a topological order nobody reads."""
    return sorted(definitions)


def check_suppressions_resolve(definitions: dict[str, dict], roots: list[tuple[str, dict]]) -> None:
    """Fails when a suppression names a property the schema no longer has.

    ``SUPPRESSED_FIELDS`` is keyed by plain strings, so a field renamed upstream
    would quietly stop matching and the surface AgentBar declined would return
    to the build with nothing to announce it. A refusal has to be checked, not
    assumed.
    """
    owners: dict[str, dict] = dict(definitions)
    owners.update(dict(roots))
    for node in list(owners.values()):
        for branch in node.get("oneOf", []):
            title = branch.get("title")
            if title:
                owners[title] = branch

    for key in sorted(SUPPRESSED_FIELDS):
        owner, _, prop = key.partition(".")
        node = owners.get(owner)
        if node is None or prop not in node.get("properties", {}):
            sys.exit(
                f"error: suppressed field {key} is not in the schema. It was renamed or "
                "removed upstream, so the suppression no longer refuses anything — "
                "update SUPPRESSED_FIELDS to match the current contract."
            )


def generate() -> str:
    definitions, roots = load_roots()
    check_suppressions_resolve(definitions, roots)
    reachable = reachable_definitions(definitions, roots)
    definitions = {name: node for name, node in definitions.items() if name in reachable}
    # Wrapped for the same reason the per-type note is: the header's width is
    # decided by a reason string somebody will one day lengthen.
    suppressed_lines: list[str] = []
    for key, reason in sorted(SUPPRESSED_FIELDS.items()):
        current = f"//   {key} —"
        for word in reason.split():
            if len(current) + 1 + len(word) > 96:
                suppressed_lines.append(current)
                current = "//    "
            current += f" {word}"
        suppressed_lines.append(current)
    suppressed = "\n".join(suppressed_lines)
    lines = HEADER.format(suppressed=suppressed).split("\n")
    lines.append("")
    for name in dependency_order(definitions):
        lines += emit(name, definitions[name])
    for name, node in roots:
        lines += emit(name, node)
    text = "\n".join(lines)
    # Collapse the blank line every declaration ends with against the next one.
    text = re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n"
    return text


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate())
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
